import { chromium } from '@playwright/test';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:5173/marvel-universe/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1800);
await page.screenshot({ path: 'qa/desktop-hero.png' });
await page.locator('#avengers').scrollIntoViewIfNeeded();
await page.waitForTimeout(1000);
await page.screenshot({ path: 'qa/desktop-roster.png' });
await page.locator('#saga').scrollIntoViewIfNeeded();
await page.waitForTimeout(1000);
await page.screenshot({ path: 'qa/desktop-saga.png' });
await page.getByRole('button', { name: 'Explore Iron Man, Tony Stark', exact: true }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: 'qa/desktop-dossier.png' });
await page.keyboard.press('Escape');
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://localhost:5173/marvel-universe/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'qa/mobile-hero.png' });
await page.locator('#avengers').scrollIntoViewIfNeeded();
await page.waitForTimeout(800);
await page.screenshot({ path: 'qa/mobile-roster.png' });
console.log(JSON.stringify({ errors, overflow: await page.evaluate(() => ({ body: document.body.scrollWidth, viewport: window.innerWidth })), images: await page.locator('img').evaluateAll(imgs => imgs.map(img => ({ src: img.getAttribute('src'), loaded: img.complete && img.naturalWidth > 0 }))) }, null, 2));
await browser.close();
